name: CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install'
        run: npm install

      - name: 'Build'
        run: ng build --configuration staging

      - name: 'Deploy'
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
